feat: спринт13 начало shareit
tochmary/java-shareit pull request #1
Opened 2022-07-25 19:58 UTC by tochmary

2022-07-26 12:42 UTC, Fleaman777 requested changes

2022-07-26 12:42 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  package ru.practicum.shareit.item;
можно сразу добавить пекеджы controller, service и др.,
что бы потом, когда будут появляться новые контроллеры/сервисы относящиеся к айтему, не пришлось все разносить по соответствующим пакетам

2022-07-26 12:42 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    }
есть мнение, что в конструктор лучше не передавать больше 3-4 аргументов, это ухудшает восприятие кода, 
как альтернатива, использовать билдер 

исправлять или нет, на твое усмотрение

2022-07-26 12:42 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.getItemsByUserId(userId).stream().noneMatch(i -> i.getId() == itemId)) {
эту проверку лучше вынести в отдельный приватный метод, с таким названием, что бы было понятно, когда метод вернет тру, а когда фолс. 

это нужно для того, что бы при быстром просмотре кода, из названия сложилось понимание, в каком случае выбросится NotFoundException

2022-07-26 12:42 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return UserMapper.toUserDto(userService.addUser(UserMapper.toUser(userDto)));
получилась достаточно большая вложенность, что ухудшает восприятие.
возможно стоит ее разделить добавив локальные переменные, или перенести логику в сервис

2022-07-26 13:19 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .collect(Collectors.toList());
по хорошему, полной логикой преобразования должен заниматься или трансформер, или маппер, а контроллер просто вернет то, что ему отдадут маппер/трансформер.

т.к. у нас сейчас примитивная логика маппинга, то получается не сложный стрим, который можно оставить 
но в будущем, лучше подобные вещи выполнять в спец. для это сущностях

2022-07-27 08:21 UTC, tochmary commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    }
пока не стала исправлять

2022-08-08 08:39 UTC, merged