Add docker
tochmary/java-shareit pull request #4
Opened 2022-09-08 20:42 UTC by tochmary

2022-09-10 07:48 UTC, Fleaman777 requested changes

2022-09-10 07:48 UTC, Fleaman777 commented on shareit-gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +    public ResponseEntity<Object> bookItem(@RequestHeader("X-Sharer-User-Id") long userId,
X-Sharer-User-Id можно было бы вынести в константу

2022-09-10 07:48 UTC, Fleaman777 commented on shareit-gateway/src/main/java/ru/practicum/shareitgateway/item/ItemClient.java
> +        return post("/" + itemId + "/comment", userId, commentDto);
вроде бы и неплохо выглядит конкатенация строк через "+",
но немного глаз режет, особенно если учесть, что это делается в аргументе,

попробуй может как-нибудь вынести эту конкатенаицю в отдельный общий метод,
или, например использовать StringUtils.join в apache библиотеке,
или еще как-нибудь.

fyi: вообще в этой библиотеке очень много хороших методов по работе со строками, обязательно будешь ее использовать

2022-09-10 07:48 UTC, Fleaman777 commented on shareit-gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +                                              @Positive @RequestParam(name = "size", defaultValue = "20") Integer size) {
на сколько я помню, если название аргумента совпадает с названием параметра, то name явно можно не указывать,
посмотри этот момент, если так, то name можно будет убрать

2022-09-10 07:48 UTC, Fleaman777 commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=user
в разных проектах может быть по разному,
но во всех, в которых я был, значения переменным присваились через двоеточие т.е.,
POSTGRES_DB: shareit
POSTGRES_USER: user
POSTGRES_PASSWORD: user

так сказать, дело вкуса 
если нравится свой вариант, можно не исправлять

2022-09-10 08:58 UTC, tochmary commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=user
оставила как было, как нас учили на Практикуме)

2022-09-11 10:31 UTC, Fleaman777 approved these changes

2022-09-11 10:31 UTC, Fleaman777 commented on shareit-gateway/src/main/java/ru/practicum/shareitgateway/common/Utility.java
> +        return StringUtils.join("/", StringUtils.join(args, ""));
здорово, отличный получился подход

2022-09-11 10:31 UTC, Fleaman777 commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=user
понял, хорошо)

2022-09-11 12:57 UTC, merged